project:
  type: book
  output-dir: docs

book:
  title: Tips for using Git and GitHub
  chapters:
    - part: 01-index.qmd
      chapters:
        - 01-01-intro-git.qmd
        - 01-02-installing-git.qmd
        - 01-03-intro-github.qmd
        - 01-04-git-and-github-workflow.qmd
        - 01-05-making-pull-request.qmd
        - 01-06-merging-branch-locally.qmd
        - 01-07-rebasing-branch.qmd
        - 01-08-common-errors.qmd
        - 01-09-installing-python-and-os.qmd
        - 01-10-os-repos.qmd
        - 01-11-additional-topics.qmd
        - 01-12-short-practical.qmd
    - part: 02-index.qmd
      chapters:
        - 02-01-study-definition.qmd
        - 02-02-r-code.qmd
        - 02-03-outputs.qmd
        - 02-04-misc.qmd
        - 02-05-docker-apple-silicon.qmd
    - 99-session-info.qmd
  repo-url: https://github.com/remlapmot/git-and-github-for-os
  repo-actions: source
  repo-branch: master
  site-url: https://remlapmot.github.io/git-and-github-for-os/

format:
  html:
    toc: true
    link-external-icon: true
    theme: cosmo
    css: styles.css
    code-overflow: wrap
